require("my.opts")
require("my.maps")

require("lze").register_handlers(require("lzextras").lsp)

vim.cmd.colorscheme(nixCats("colorscheme"))

require("my.colorizer")
require("my.comment")
require("my.completions")
require("my.diagnostics")
require("my.finder")
require("my.format")
require("my.git-signs")
require("my.lint")
require("my.lsp")
require("my.netrw")
require("my.quickfix")
require("my.sessions")
require("my.surround")
