#!/usr/bin/env bash

set -euo pipefail

nixos_dir="$(nix eval '#.nixosDir')"

sudo cp \
  --force \
  --update=all \
  --symbolic-link \
  --one-file-system \
  "${nixos_dir}"/* /etc/nixos/

sudo nixos-rebuild "${@}"
